services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_CONTAINER_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: django_backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "${BE_HOST_PORT}:${BE_CONTAINER_PORT}"
    depends_on:
      - db
    
  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "${FE_HOST_PORT}:${FE_CONTAINER_PORT}"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql_data:
