# Generated by Django 4.2.11 on 2025-07-11 06:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinemas_name', models.CharField(max_length=100)),
                ('cinemas_address', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cinema',
                'db_table': 'cinemas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=255, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'db_table': 'genres',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('age_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('trailer_url', models.TextField(blank=True, null=True)),
                ('movie_poster_url', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'db_table': 'movies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=100, unique=True)),
                ('permission_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'db_table': 'permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.cinemas')),
            ],
            options={
                'verbose_name': 'Room',
                'db_table': 'rooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SeatTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type_name', models.CharField(max_length=50, unique=True)),
                ('seat_type_description', models.TextField(blank=True, null=True)),
                ('seat_type_color_code', models.CharField(blank=True, max_length=10, null=True)),
                ('seat_type_status', models.CharField(blank=True, max_length=20, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seat Type',
                'db_table': 'seat_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_address', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.roles')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Showtimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('base_price', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.movies')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.rooms')),
            ],
            options={
                'verbose_name': 'Showtime',
                'db_table': 'showtimes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.rooms')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.seattypes')),
            ],
            options={
                'verbose_name': 'Seat',
                'db_table': 'seats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SeatPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.seattypes')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.showtimes')),
            ],
            options={
                'verbose_name': 'Seat Price',
                'db_table': 'seat_prices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.CharField(max_length=100, unique=True)),
                ('admin_password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.roles')),
            ],
            options={
                'verbose_name': 'Admin',
                'db_table': 'admins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SeatStatusInShowtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked')], max_length=10)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.seats')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.showtimes')),
            ],
            options={
                'verbose_name': 'Seat in showtime',
                'db_table': 'seat_status_in_showtime',
                'unique_together': {('showtime', 'seat')},
            },
        ),
        migrations.CreateModel(
            name='MoviesGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.genres')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.movies')),
            ],
            options={
                'verbose_name': 'Movie Genre',
                'db_table': 'movies_genres',
                'managed': True,
                'unique_together': {('movie', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='booking.roles')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.permissions')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'db_table': 'role_permissions',
                'managed': True,
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
